<?xml version="1.0" encoding="utf-8"?><Database Name="FeedbackApp" Class="studentDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=JOHN-PC\SQLEXPRESS;Initial Catalog=FeedbackApp;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="FeedbackAppConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.students" Member="authStus">
    <Type Name="authStu">
      <Column Name="studentID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="studentFName" Type="System.String" DbType="NChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="studentLName" Type="System.String" DbType="NChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="courseID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>